# Generated by Django 4.1.3 on 2023-06-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='sku',
            field=models.CharField(max_length=11),
        ),
    ]
