# Generated by Django 4.1.3 on 2023-06-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_furniture_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='image',
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='sku',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
