# Generated by Django 4.1.3 on 2023-06-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_furniture_image_furniture_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveditem',
            name='quantity',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
